@echo off
echo Starting PRODUCTION with real API data...

echo Use ".env" environment settings for production mode...
set USE_TEST_DATA=false

echo Clearing any cached data...
python -c "from scheduler import data_scheduler; data_scheduler.clear_cache()"

echo Starting application with production data (Columbia)...
python app.py

pause